spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    deserialization:
      read-unknown-enum-values-as-null: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reservation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      concurrency: 3

custom:
  kafka:
    topic:
      bank-transfer: bank-transfer-payment-update
    trusted-packages: "*"

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3

credit:
  card:
    base-url: http://localhost:9090/credit-card-payment-api

logging:
  level:
    root: INFO
    com.marvel.reservation: DEBUG


  #key clock related settings. (8082 port used by Keyclock).
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/demo-realm


## Key-clock command need to run : podman run --name keycloak  -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak start-dev